//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship_Final_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attack
    {
        public int ID { get; set; }
        public int Coordinate { get; set; }
        public bool Hit { get; set; }
        public int GameFK { get; set; }
    
    }
}
