//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship_Final_
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameShipConfiguration
    {
        public int ID { get; set; }
        public string PlayerFK { get; set; }
        public int Ship { get; set; }
        public int Coordinate { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual GameShipConfiguration GameShipConfigurations1 { get; set; }
        public virtual GameShipConfiguration GameShipConfiguration1 { get; set; }
        public virtual Player Player { get; set; }
    }
}
